const C_TEXT_PRINC = "Passei férias ao longo da costa de Amalfi e me apaixonei pelos proprietários e pela equipe da Lo Scoglio em Nerano.Eles me influenciaram de uma forma que parece muito mais substancial do que qualquer outro momento ou evento já me tocou.";


const C_DESC = "Proprietário rural sai da falência com $ 8,5 milhões";
const C_DESC_SEC =
    "O cliente do Centro-Oeste se recupera de pagamentos inadimplentes com a estrutura financeira flexível da AgAmerica. Não existe um tamanho único para todos.";

const C_DESC_SEC_MOBILE =
    "O cliente do Centro-Oeste se recupera de pagamentos..";

const link = "Vnxn46sMNyk";

const slideImage = [
    "https://images.unsplash.com/photo-1444830038442-c43db8ffb5ce?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1628468734774-022968574c56?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1619974100405-20da2b00e666?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1027&q=20",
    "https://images.unsplash.com/photo-1619765263116-4bf31410df19?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1611942590102-d0660a2463b6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1596883072150-f5d25584e064?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1614788888661-8c00cdb70add?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1566839750901-ff71526268e7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1563372057-bcd0e4593fbe?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1531257514241-c2ef708aa29c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1587973367556-9237e51df783?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1609252509027-3928a66302fd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1629144254104-90afaf484fe9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
    "https://images.unsplash.com/photo-1563201515-adbe35c669c5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=20",
];

export default [
    {
        search: "familia-gaio",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1577368163048-4aac95ca7488?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    },
    {
        search: "Segundo",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1574943320219-553eb213f72d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1024&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio1",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "terceiro",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1492496913980-501348b61469?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=334&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio2",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "quarto",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1515150144380-bca9f1650ed9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=334&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio3",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "quinto",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1622770742416-04431011b208?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1189&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio4",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "sexto",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1622630196242-57fe99286fc2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1267&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio5",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "setimo",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1595263930044-33a008c0e32b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=634&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio6",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "oitavo",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1527847263472-aa5338d178b8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1353&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio7",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    },
    {
        search: "nono",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1530267981375-f0de937f5f13?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1350&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio8",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "decimo",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1563201515-adbe35c669c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1353&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio9",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "decimoSeg",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1623211269755-569fec0536d2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio10",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    },
    {
        search: "decimoTerc",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1606701587683-c4b1b22c59d4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=676&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio11",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    }, {
        search: "14",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1505471768190-275e2ad7b3f9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=634&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio12",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    },
    {
        search: "15",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1609583120830-7ede0764d401?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio13",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    },
    {
        search: "16",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1600266189529-58cc5dc3d63d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio14",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    },
    {
        search: "17",
        title: "empréstimos alternativos de terra",
        desc: C_DESC,
        descSec: C_DESC_SEC,
        descSecMobile: C_DESC_SEC_MOBILE,
        buttonDesc: "Asisstir",
        link: link,
        img:
            "https://images.unsplash.com/photo-1565321643328-3f919879cd3b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=664&q=80",
        slideImage: slideImage,
        titleBtnNextPrev: "Familia Gaio15",
        textPrinc: C_TEXT_PRINC,
        textSec: C_TEXT_PRINC,
        textThird: C_TEXT_PRINC,
    },
];
